version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/clustering/sharding-sqlserver"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/reliability/rabbitmq-backpressure"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
