<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latestmajor</LangVersion>
    <IsPackable>false</IsPackable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka.Hosting.TestKit" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReliableRabbitMQ.Consumer\ReliableRabbitMQ.Consumer.csproj" />
    <ProjectReference Include="..\ReliableRabbitMQ.Shared\ReliableRabbitMQ.Shared.csproj" />
  </ItemGroup>

</Project>
