<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(NetRuntime)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Streams.Amqp.RabbitMq" />
        <PackageReference Include="Akka.Cluster.Hosting" />
    </ItemGroup>

</Project>
