<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(NetRuntime)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Cluster.Sharding"/>
        <PackageReference Include="Akka.Cluster.Hosting"/>
        <PackageReference Include="Bogus" />
        <PackageReference Include="Grpc.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Serialization\Proto\CqrsSqlServer.Messages.proto" GrpcServices="None" />
    </ItemGroup>

</Project>
